robot_backend_interface_msgs/Robot robot_status # Service request via robot_backend_interface_msgs/msg/UpdateRobotstatus type
---
std_msgs/String response # Service response via std_msgs/msg/String type. It can be 'true' or 'false'